/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    AStyleProvider: typeof import('ant-design-vue/es')['StyleProvider']
    ATable: typeof import('ant-design-vue/es')['Table']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Dialog: typeof import('./src/components/dialog/index.vue')['default']
    MessageBox: typeof import('./src/components/Message/MessageBox.vue')['default']
    MyToast: typeof import('./src/components/MyToast/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Svg: typeof import('./src/components/Svg/index.vue')['default']
    Toast: typeof import('./src/components/toast/index.vue')['default']
  }
}
